shiguredo-webrtc-build/webrtc-build

build.ios.sh, scripts/package_webrtc_ios.sh
- iOS のデバッグ・ビルドを追加しました
- 変更後のディレクトリは以下のような構成になっています
```
$ tree -L 3 --filelimit 10
.
├── NOTICE
├── VERSIONS
├── debug
│   ├── WebRTC.dSYM
│   │   └── Contents
│   ├── WebRTC.framework
│   │   ├── Headers
│   │   ├── Info.plist
│   │   ├── LICENSE.md
│   │   ├── Modules
│   │   ├── WebRTC
│   │   └── build_info.json
│   └── lib
│       └── libwebrtc.a
├── include [25 entries exceeds filelimit, not opening dir]
└── release
├── WebRTC.framework
│   ├── Headers
│   ├── Info.plist
│   ├── LICENSE.md
│   ├── Modules
│   ├── WebRTC
│   └── build_info.json
└── lib
└── libwebrtc.a
13 directories, 12 files
```
=> iOS のデバッグ・ビルドを追加

build.macos_x86_64.sh
- mac x86_64 の `libwebrtc.a` に含まれるファイルを修正
#12 の対応にてデバッグ/リリースビルドへ対応を致しましたが、その際 ar コマンドでアーカイブするディレクトリを誤って変更してしまっていました。今回、コマンドの実行ディレクトリを元に戻しています。
=> アーカイブ対象のディレクトリをobj配下に修正

build.macos_arm64.sh
#12 #13 と同様に、macOS arm64に対してもObjCのヘッダーファイルの出力を行いました。
主な対応内容は以下になります。
- ObjCヘッダーファイルを出力するために `mac_framework_objc` オプションを追加
- `Info.plist` の書き換えを行う
- debug/releaseビルドの作成
なお、ビルド成功時の `webrtc.tar.gz` は展開すると以下の構成になります。
```
webrtc
├── NOTICE
├── VERSIONS
├── debug
│   ├── WebRTC.dSYM
│   │   └── Contents
│   ├── WebRTC.framework
│   │   ├── Headers
│   │   ├── Modules
│   │   ├── Resources
│   │   ├── Versions
│   │   └── WebRTC
│   └── lib
│       └── libwebrtc.a
├── include
│   ├── api
(中略)
│   └── video
└── release
├── WebRTC.framework
│   ├── Headers
│   ├── Modules
│   ├── Resources
│   ├── Versions
│   └── WebRTC
└── lib
└── libwebrtc.a
```
=> macOS(arm64)むけのObjCヘッダー込みのWebRTC.frameworkを作成

patches/ios_manual_audio_input.patch
lockForConfiguration の実装が recursive lock から non-recursive lock に変更されたタイミングで、 `patches/ios_manual_audio_input.patch` のコードが原因で iOS でロックの競合が発生し、 iOS で映像・音声の送受信ができなくなっていた問題を修正しました
=> iOS で発生したロックの競合を解消する

CHANGES.md, android/Dockerfile, patches/android_onremovetrack.patch, scripts/package_webrtc_android.sh
- libwebrtc_onremovetrack.aar を廃止して、 libwebrtc.aar に android_onremovetrack.patch を適用しました
=> libwebrtc_onremovetrack.aar を libwebrtc.aar に統合する

build.macos_arm64.sh, build.macos_x86_64.sh, patches/ios_simulcast.patch
macOSにてRTCVideoEncoderFactorySimulcast を利用可能にするため、 `ios_simulcast.patch` を  macOS向けのビルドスクリプトに追加します。
ただし、 `ios_simulcast.patch` をそのまま `build.macos_xx.sh` に組み込むだけでは、warningが発生し、ビルドがエラーになってしまいます。
これは、macOSでのビルド実行時に構築されるコマンド内に `-Wobjc-missing-property-synthesis` が組み込まれているためです。
そのため、 `@synthesize` を パッチに追記し、warningを解消することにしています。
=> RTCVideoEncoderFactorySimulcastをmacOSでも使用可能にする

build.macos_arm64.sh, build.macos_x86_64.sh, patches/macos_statistics.patch
[背景]
Sora iOS SDKでは `RTCStatisticsReport` を利用していますが、 `RTCStatisticsReport` はiOS向けにのみヘッダーが公開されています。現状macOSで統計情報を送信するには `RTCLegacyStatsReport` のみしか使うことができません。
`RTCLegacyStatsReport` と `RTCStatisticsReport` は内部的に利用しているStatsのクラスが異なることから、macOSではiOSとStatsの中見が異なってしまいます。
[対応内容]
macOSでもiOSと同様に `RTCStatisticsReport` を利用可能にするためにヘッダーを公開します。
[メリット]
- リモート統計情報の送信箇所をiOSとmacOSで実装を合わせることができます
- Soraのリモート統計情報APIのレスポンスもiOSと同様な形で確認できるようになります
[デメリット]
- 特にありません
=> macOSでもiOSと同様のリモート統計情報を送信できる

build.macos_arm64.sh, build.macos_x86_64.sh, scripts/package_webrtc_macos.sh
1. webrtc m93にてiOS向けに `WebRTC.xcframework` が出力されるようになりました
2. 従来、CocoaPodsで `WebRTC.framework` の配布を行う場合、CocoaPods単体では `WebRTC.dSYM` をアプリケーションのアーカイブに含めることができず、利用者側で何らかのスクリプトを書く必要がありました。
macOS `x86_64` / `arm64` 両方のアーキテクチャにて以下の対応をしています。
- debug/release ビルドに関わらずdSYMを出力する
- ビルド済みの `WebRTC.framework` / `WebRTC.dSYM` を基に `WebRTC.xcframework` を生成する
- release バイナリのクラッシュレポートをフレームワーク利用者が読めるようになる
- CocoaPods が `1.9` から `.xcframework` に対応したことで、`.xcframework` を使えば `WebRTC.dSYM` のエクスポートが容易になる
- 特にありません
今回、`WebRTC.framework` と `WebRTC.dSYM` は従来通り `webrtc.tar.gz` 内に残したままにしています。
理由としては、 `x86_64` と `arm64` の両アーキテクチャ向けの単一の`WebRTC.xcframework` を提供したい利用者は自身で `xcodebuild -create-xcframework` を行っていただくことになります。その際 `lipo` コマンドでユニバーサルな `WebRTC.framework` 、`WebRTC.dSYM` を事前に作る必要があるためです。
=> macOSでxcframeworkに対応する

CHANGES.md, build.macos_arm64.sh, build.macos_x86_64.sh, build.windows.ps1, patches/README.md, patches/libjpeg_turbo_mangle_jpeg_names.patch, raspberry-pi-os_armv6/Dockerfile, raspberry-pi-os_armv7/Dockerfile, raspberry-pi-os_armv8/Dockerfile, ubuntu-18.04_armv8/Dockerfile, ubuntu-18.04_x86_64/Dockerfile, ubuntu-20.04_x86_64/Dockerfile
libwebrtc (chromium) には、利用している libjpeg がシステムの libjpeg と混ざることを防ぐ仕組みがあります。
参照: https://source.chromium.org/chromium/chromium/src/+/master:third_party/libjpeg_turbo/README.chromium;l=30-34;drc=ff19e5b2e176c61d552f68768e0e051867745321
(おそらく) https://chromium-review.googlesource.com/c/chromium/deps/libjpeg_turbo/+/2872069 が原因でその仕組が壊れて、 momo の一部の機能が WebRTC M93 で動作しなくなっている問題を修正します。
当面は、 momo で利用される可能性のある全てのバイナリにパッチを適用してはどうかと考えています。
=> libjpeg_turbo の ビルド時に MANGLE_JPEG_NAMES を指定する

build.ios.sh
[背景]
Sora iOS SDK をビルドしていた時に、WebRTC.xcframeworkにbitcodeが存在しない旨のエラーメッセージが出力されました。
確認したところ、Unity向けのビルドとそうでないビルドでbitcodeが異なっていることに気づきました。
[対応内容]
以下2点の設定変更を行なっています。
- iOS向けのwebrtc-buildにおいて ~~relase ビルドの際には~~ debug/release ビルド問わず bitcodeを有効化する
- ~~以前の設定に戻す形になります~~
- dSYMの出力もUnity向けバイナリと合わせて常にtrueとする
[メリット]
- 従来通り、リリースビルド時にbitcode=YESによるビルドが可能になる
- releaseビルド向けのdebug symbolを開発者が使うことができるようになる
[デメリット]
- 特になし
=> iOS向けビルド時の出力設定を合わせる

build.ios.sh
[背景]
#31 にてiOSビルド時のbitcodeの有効化設定を追加しましたが、不足がありました。
`src/build/config/ios/BUILD.gn` を確認したところ、以下のような処理ブロックがあり、`use_xcode_clang=true` でビルドする必要があります。
```
if (use_xcode_clang && enable_ios_bitcode && target_environment == "device") {
if (is_debug) {
common_flags += [ "-fembed-bitcode-marker" ]
} else {
common_flags += [ "-fembed-bitcode" ]
}
}
```
[対応内容]
- `use_xcode_clang=true` を追加
[相談事項]
81f3a809225f32bdf4c4905990a6c20e9d11962b を拝見するに、意図的にXCodeのClang利用を回避しているように見受けられるのですが、私の知識が浅く、判断しかねるため、 `use_xcode_clang=true` を入れて良いかご意見いただきたいです。
=> bitcodeを有効にするためにはuse_xcode_clang=trueが必要だった

patches/android_simulcast.patch
- SimulcastVideoEncoderFactory class の fallback に null を渡せるようにしました
- 参照: simulcast_encoder_adapter 側では fallback_factory に null が渡されることは想定されているようです https://source.chromium.org/chromium/chromium/src/+/main:third_party/webrtc/media/engine/simulcast_encoder_adapter.h;l=47-48;drc=59947d28711f9ecec460e7ae83a769be5bd70794
> // `fallback_factory`, if non-null, is used to create fallback encoder that
> // will be used if InitEncode() fails for the primary encoder.
Sora Android SDK で利用している libwebrtc のバージョンを更新したところ、サイマルキャストがクラッシュすることを確認しました
この修正は、そのクラッシュを修正する過程で必要になりました
=> SimulcastVideoEncoderFactory の fallback に null を渡せるようにする

CHANGES.md, patches/README.md, patches/android_hardware_video_encoder.patch, run.py
- Android の HardwareVideoEncoder に実装された解像度の制限を回避するパッチを追加しました
=> Android の HardwareVideoEncoder に実装された解像度の制限を回避するパッチを追加する

patches/ios_proxy.patch
- プロキシを設定する API を Swift から利用しようとしたところ、certificateVerifier が必須になっていたので `nullable` を付与して optional にしました
=> ios_proxy.patch を修正

.github/workflows/build.yml, .github/workflows/daily.yml, README.md, multistrap/ubuntu-22.04_armv8.conf, run.py
JetPack 6.0 の対応として、 multistrap の設定を追加しました
(JetPack 6.0 から Jetson Linux が Ubuntu 22.04 ベースになります)
JetPack 6.0 は Developer Preview のため、動作は未確認としています
[JetPack SDK 6.0 DP | NVIDIA Developer](https://developer.nvidia.com/embedded/jetpack-sdk-60dp)
=> JetPack 6.0 に対応するため ubuntu-22.04_armv8 のビルドを追加する

CHANGES.md, patches/h265.patch, run.py
oneVPL H265 対応 https://github.com/shiguredo-webrtc-build/webrtc-build/pull/67 を master ブランチに取り込むための PR です
上記の PR から必要なコミットを cherry-pick しています
=> oneVPL H265 対応

.github/workflows/build.yml, CHANGES.md
変更内容
- [UPDATE] GitHub Actions Android のビルド環境を Ubuntu 22.04 に上げる
---
This pull request includes updates to the GitHub Actions workflow and documentation. The most important changes include updating the build environment for the Android job and documenting this change in the `CHANGES.md` file.
Updates to GitHub Actions workflow:
* [`.github/workflows/build.yml`](diffhunk://#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721L122-R122): Changed the `runs-on` version for the Android job from `ubuntu-20.04` to `ubuntu-22.04`.
Documentation updates:
* [`CHANGES.md`](diffhunk://#diff-d975bf659606195d2165918f93e1cf680ef68ea3c9cab994f033705fea8238b2R15-R19): Added an entry to document the update of the Android build environment to `ubuntu-22.04`.
=> GitHub Actions の Android ビルド環境を Ubuntu 22.04 に上げる

CHANGES.md, patches/h265_ios.patch
Sora iOS SDK を利用したアプリをビルドしてアーカイブをアップロードする際に以下のようなエラーが出たため、
`_kVTVideoEncoderSpecification_RequiredLowLatency` をパッチから削除する対応を行います。
- メッセージ内容
`The app references non-public symbols in Payload/DataChannelSample.app/Frameworks/WebRTC.framework/WebRTC: _kVTVideoEncoderSpecification_RequiredLowLatency`
---
This pull request includes significant changes to address an issue with uploading iOS apps containing the `libwebrtc` library to App Store Connect. The changes focus on removing references to a non-public symbol that caused the upload failure. Below are the most important changes:
* Removed the reference to `kVTVideoEncoderSpecification_RequiredLowLatency` from the `h265_ios.patch` file to resolve the issue with App Store Connect rejecting the app due to the use of a non-public symbol. …
=> kVTVideoEncoderSpecification_RequiredLowLatency を h265_ios.patch から削除する

CHANGES.md, patches/ios_add_scale_resolution_down_to.patch
- 2025-01-31 [UPDATE] iOS の scaleResolutionDownTo のプロパティの setter を assign から copy に変更する
---
This pull request includes updates to the iOS SDK to change the `scaleResolutionDownTo` property's setter from `assign` to `copy` and updates the `CHANGES.md` file to reflect this change.
* Changed `maxWidth` and `maxHeight` properties in `RTCRtpEncodingParameters.h` from `assign` to `copy`.
* Added `scaleResolutionDownTo` property to `RTCRtpEncodingParameters` class and updated the implementation to synthesize this property. [[1]](diffhunk://#diff-4348d0dbf38c7476603b0aa4ede0c5c8c55bec1756940912bde8b6a5c12d497eL45-R53) [[2]](diffhunk://#diff-4348d0dbf38c7476603b0aa4ede0c5c8c55bec1756940912bde8b6a5c12d497eL65-R65)
* Updated `CHANGES.md` to include the change to the `scaleResolutionDownTo` property.
=> iOS の scaleResolutionDownTo のプロパティの setter を assign から copy に変更する

CHANGES.md, patches/ios_manual_audio_input.patch
- 2025-07-02 [FIX] iOS でオーディオ処理が行われなくなる不具合を修正
- https://source.chromium.org/chromium/_/webrtc/src/+/11f487e72f22d92104c2b8770793285d5fe5dfa9 により、InitPlayOrRecord 内で audio_is_initialized_ を true に設定する仕様へ変更
- 既存の ios_manual_audio_input.patch は InitPlayOrRecord で早期リターンしていたため audio_is_initialized_ が設定されず、iOS で再生／録音が機能しなかった
- 早期リターン箇所にも audio_is_initialized_ = true を追加し、初期化漏れを解消
=> InitPlayOrRecord の早期リターン部分に audio_is_initialized_ = true を追加する

CHANGES.md, patches/ios_add_scale_resolution_down_to.patch
https://github.com/shiguredo/sora-ios-sdk/pull/262 の iOS SDK の修正で、RTCResolutionRestriction 自体をコピーする必要が出てきたため、RTCResolutionRestriction に NSCopying プロトコルを実装しました。
iOS SDK と組み合わせて動作確認をし、期待通りの挙動（コピーできる）をしていることは確認済です。
=> iOS 向けの RTCResolutionRestriction に NSCopying プロトコルを実装する
